clc
clear all
ThisFilePath = cd;
addpath(genpath(ThisFilePath));
calibrationTxt = 'EBT4_10Gy_48hours_v2.TXT';
OutputFolder = 'T:\Physics_Research\LABS\LAB_Ken_Wang\GroupMeeting\LixiangGuo\File Transfer - LG\Film dosimetry\Film_dosimetry_algorithm_file\Triple Channel\results_v3';

for i = 8:8
    close all
    beforeTif = [num2str(i), ' before.tif'];
    afterTif  = [num2str(i), ' after.tif'];
    OutputPrefix = num2str(i);
    out = reconstructDoseTripleChannelRegistered( ...
        calibrationTxt, ...
        beforeTif, ...
        afterTif, ...
        'OutputFolder', OutputFolder, ...
        'OutputPrefix', OutputPrefix, ...
        'DPI',300,...
        'ROISize_mm', [5 5], ...
        'ShowFigures', true, ...
        'SaveFigures', true);
    cd(OutputFolder)
end

